# Generated by Django 5.2.3 on 2025-06-30 02:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('parentezco', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.RemoveField(
            model_name='carrera',
            name='email',
        ),
        migrations.RemoveField(
            model_name='carrera',
            name='profesion',
        ),
        migrations.AddField(
            model_name='carrera',
            name='fechaDeInicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
